vars:
  - videos:
    - title: "ActInf Textbook Group ~ Cohort 1 ~ Meeting 1 (Onboarding)"
      url: https://www.youtube.com/watch?v=ogV63M3uTlQ

stages:
  get_description_from_youtube:
    foreach:
      ${videos}
    do:
      cmd: >
        python3 src/get_description_from_youtube.py
        --input_url "${item.url}"
        --output_description_file_path "data/descriptions/${item.title}.txt"
      deps:
        - src/get_description_from_youtube.py
        - data/.initial_dvc_dep.md
      outs:
        - data/descriptions/${item.title}.txt:
            cache: false
  get_audio_from_url:
    foreach:
      ${videos}
    do:
      cmd: >
        youtube-dl -x
        --audio-format mp3
        -o "data/audio/${item.title}.mp3"
        "${item.url}"
      deps:
        - data/.initial_dvc_dep.md
      outs:
        - data/audio/${item.title}.mp3
  transcript_audio:
    foreach:
      ${videos}
    do:
      cmd: >
        whisper
        --language English
        --output_dir data/transcripts
        --output_format txt
        "data/audio/${item.title}.mp3"
      deps:
        - data/audio/${item.title}.mp3
      outs:
        - data/transcripts/${item.title}.txt:
            cache: false
  summarize_transcript:
    foreach:
      ${videos}
    do:
      cmd: >
        python3 src/summarize_transcript.py
        --input_transcript_file_path "data/transcripts/${item.title}.txt"
        --output_summary_file_path "data/summaries/${item.title}.txt"
      deps:
        - src/summarize_transcript.py
        - data/transcripts/${item.title}.txt
      outs:
        - data/summaries/${item.title}.txt:
            cache: false
  extract_keywords_from_description_and_summary:
    foreach:
      ${videos}
    do:
      cmd: >
        python3 src/extract_keywords_from_description_and_summary.py
        --input_title "${item.title}"
        --input_description_file_path "data/descriptions/${item.title}.txt"
        --input_summary_file_path "data/summaries/${item.title}.txt"
        --output_keywords_file_path "data/keywords/${item.title}.txt"
      deps:
        - src/extract_keywords_from_description_and_summary.py
        - data/descriptions/${item.title}.txt
        - data/summaries/${item.title}.txt
      outs:
        - data/keywords/${item.title}.txt:
            cache: false
